spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    platform: h2
    url: jdbc:h2:mem:datajpa
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jackson.serialization.indent-output: true

logging.level.org.hibernate.SQL: debug