spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
google:
  client:
    clientId: 409861431217-h8g2em9bn6aa85e59io2ikl79gfoo9bn.apps.googleusercontent.com
    clientSecret: W8VdLZIDpsh-3hWhl6QN4Hng
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false
      
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
#office365:
#  client:
#    clientId: 836613ac-92a5-441d-9554-711cb75c474a
#    clientSecret: gxgfJ707;wneLXEGLZ88((}
#    accessTokenUri: https://login.microsoftonline.com/common/oauth2/token
#    userAuthorizationUri: Auth URL – https://login.microsoftonline.com/common/oauth2/authorize
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri:   