spring:
  jackson:
    serialization:
      indent-output: true
      
security:
  oauth2:
    client:
      clientId: 409861431217-h8g2em9bn6aa85e59io2ikl79gfoo9bn.apps.googleusercontent.com
      clientSecret: W8VdLZIDpsh-3hWhl6QN4Hng
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false